### ISSUE TITLE
LiDAR 시그널 주는 방법에 대한 질문입니다.

### ISSUE THREAD

**Issue by lmkn0407** [mun9769/catkin_ws#1]

**Comment by mun9769** [comment]
해결돼서 지운건가요?

**Comment by lmkn0407** [comment]
네 아까 그 문제는 해결했어요. 그런데 다른 문제가 생겼어요.
![스크린샷, 2024-05-25 20-06-02](https://github.com/mun9769/catkin_ws/assets/169744836/d864e03c-db4c-4038-b302-2de70f1620b3)
![스크린샷, 2024-05-25 20-06-22](https://github.com/mun9769/catkin_ws/assets/169744836/3364783b-14d2-427d-bd8d-476aabfa5776)
![스크린샷, 2024-05-25 20-06-41](https://github.com/mun9769/catkin_ws/assets/169744836/3d7a1189-70ca-46dd-a1d9-570497e633f8)
혹시 첫번째 사진에서 79번째 라인에 if (obsData.ObsNum != 0) 이렇게 설정하셨잖아요? 두 번째 사진 92번 라인에서 ObsNum = LiDAR->objNum;을 하셔서 if (obsData.ObsNum != 0) 이렇게  설정하신건가요? 지금 LiDAR로 물체를 인식 중이라 세 번째 사진 위에서 두 번째 터미널에서 objNum이 1이 나오는 상황인데 첫번째 사진 83번 라인 cout이 출력되지 않아서요. 작년 코드에서는 다음에 첨부한 사진처럼 383번 째라인으로 받고 384번 째 라인에서 조건을 거는데 지금은 메카니즘이 달라진건가요??
![스크린샷, 2024-05-25 20-13-37](https://github.com/mun9769/catkin_ws/assets/169744836/15ecd9f6-a444-4139-8050-c28c741ee0cf)

**Comment by mun9769** [comment]
동일한 매커니즘입니다. 값 할당하는 것을 hpp 파일로 옮긴 것뿐이에요

**Comment by mun9769** [comment]
제가 몇가지 수정한 코드는 아래와 같습니다.
* 주석
* 값 할당 연산자
* 사용되지 않는 함수
읽기 쉽게 하기 위해 수정했습니다

**Comment by lmkn0407** [comment]
네네 그런데 objNum이 0이 아닌데도 if (obsData.ObsNum != 0) 안으로 들어가질 못해서 질문드렸습니다...

**Comment by mun9769** [comment]
맞네요! 제가 틀렸네요. 
잘 찾으셨고 내일 깃스터디 때 코드를 수정하는 방법에 대해 알려드릴게요.

**Comment by lmkn0407** [comment]
일단 작년 코드처럼 cpp파일에서 할당해서 라이다 데이터 받는 것 확인했습니다. 오늘 제가 카메라, 센서퓨전 데이터 확인하려면 해당 패키지 10시 안으로 올려주세요.

**Comment by mun9769** [comment]
패키지 업로드했습니다 확인해주세요

**Comment by lmkn0407** [comment]
혹시 카메라 위치 전달받으셨었나요?

**Comment by mun9769** [comment]
아뇨 지금 우분투 고장나서 아무것도 못하고있네요
